packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  cli:
    '@antfu/eslint-config': ^5.3.0
    '@antfu/ni': ^25.0.0
    bumpp: ^10.2.3
    czg: ^1.12.0
    eslint: ^9.35.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.1.6
    simple-git-hooks: ^2.13.1
    taze: ^19.6.0
    tsx: ^4.20.5
    typescript: ^5.9.2
    unbuild: ^3.6.1
    vite: ^7.1.5
  dev:
    stylelint: ^16.24.0
  inlined:
    '@antfu/utils': ^9.2.0
  prod:
    '@stylistic/stylelint-config': ^3.0.1
    local-pkg: ^1.1.2
    stylelint-config-recess-order: ^7.3.0
    stylelint-config-standard: ^39.0.0
    stylelint-config-standard-scss: ^16.0.0
    stylelint-config-standard-vue: ^1.0.0
    stylelint-prettier: ^5.0.3
  testing:
    execa: ^9.6.0
    sass-embedded: ^1.92.1
    tinyglobby: ^0.2.15
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    vue: ^3.5.21
    yaml: ^2.8.1
  types:
    '@types/node': ^24.5.1
  utils:
    tinyexec: ^1.0.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
