packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  dev:
    '@antfu/eslint-config': ^6.2.0
    '@antfu/ni': ^27.0.1
    bumpp: ^10.3.1
    czg: ^1.12.0
    eslint: ^9.39.0
    eslint-plugin-format: ^1.0.2
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
    stylelint: ^16.25.0
    taze: ^19.9.0
    tsdown: ^0.15.12
    tsx: ^4.20.6
    typescript: ^5.9.3
    vite: ^7.1.12
  inlined:
    '@antfu/utils': ^9.3.0
  prod:
    '@lumirelle/defu': ^1.0.2
    '@stylistic/stylelint-config': ^3.0.1
    local-pkg: ^1.1.2
    stylelint-config-html: ^1.1.0
    stylelint-config-recess-order: ^7.4.0
    stylelint-config-standard: ^39.0.1
    stylelint-config-standard-scss: ^16.0.0
    stylelint-config-standard-vue: ^1.0.0
    stylelint-prettier: ^5.0.3
  testing:
    '@vitest/coverage-v8': ^4.0.6
    sass-embedded: ^1.93.3
    tinyexec: ^1.0.1
    tinyglobby: ^0.2.15
    vitest: ^4.0.6
    vitest-package-exports: ^0.1.1
    vue: ^3.5.22
    yaml: ^2.8.1
  types:
    '@types/node': ^24.10.0

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks

verifyDepsBeforeRun: install
