packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  cli:
    '@antfu/eslint-config': ^5.4.1
    '@antfu/ni': ^26.1.0
    bumpp: ^10.3.1
    czg: ^1.12.0
    eslint: ^9.37.0
    eslint-plugin-format: ^1.0.2
    lint-staged: ^16.2.3
    simple-git-hooks: ^2.13.1
    taze: ^19.7.0
    tsdown: ^0.15.6
    tsx: ^4.20.6
    typescript: ^5.9.3
    vite: ^7.1.9
  dev:
    stylelint: ^16.25.0
  inlined:
    '@antfu/utils': ^9.3.0
  prod:
    '@stylistic/stylelint-config': ^3.0.1
    local-pkg: ^1.1.2
    stylelint-config-recess-order: ^7.3.0
    stylelint-config-standard: ^39.0.1
    stylelint-config-standard-scss: ^16.0.0
    stylelint-config-standard-vue: ^1.0.0
    stylelint-prettier: ^5.0.3
  testing:
    execa: ^9.6.0
    sass-embedded: ^1.93.2
    tinyglobby: ^0.2.15
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    vue: ^3.5.22
    yaml: ^2.8.1
  types:
    '@types/node': ^24.7.1
  utils:
    tinyexec: ^1.0.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks

verifyDepsBeforeRun: install
