/**
 * Generated by tsnapi — public API snapshot of `@lumirelle/stylelint-config`
 */
// #region Interfaces
export interface OptionsConfig {
  ignoreFiles?: string | string[];
  stylistic?: boolean | StylisticConfig;
  css?: true;
  scss?: boolean;
  less?: boolean;
  tailwindcss?: boolean;
  html?: boolean;
  vue?: boolean;
  ordered?: boolean;
  lessOpinionated?: boolean | OptionsOpinionated;
}
export interface OptionsOpinionated {
  pattern?: boolean;
  maintainability?: boolean;
}
export interface StylisticConfig {
  indent?: number | "tab";
  quotes?: "single" | "double";
  maxLineLength?: number;
}
// #endregion

// #region Types
export type StylelintConfig = Config;
export type StylelintOverrideConfig = ElementOf<NonNullable<StylelintConfig["overrides"]>>;
// #endregion

// #region Classes
export declare class ConfigComposer extends Promise<StylelintConfig | StylelintOverrideConfig> {
  private _operations;
  constructor(..._: Awaitable<Nullable<StylelintConfig | StylelintOverrideConfig>>[]);
  mix(..._: Awaitable<Nullable<StylelintConfig | StylelintOverrideConfig>>[]): ConfigComposer;
  toConfig(): Promise<StylelintConfig>;
  override then(_: (_: StylelintConfig) => any, _?: (_: any) => any): Promise<any>;
  override catch(_: (_: any) => any): Promise<any>;
  override finally(_: () => any): Promise<any>;
}
// #endregion

// #region Functions
export declare function css(_: boolean | OptionsOpinionated): Promise<StylelintConfig>;
export declare function html(_: boolean): Promise<Nullable<StylelintOverrideConfig>>;
export declare function less(_: boolean, _: boolean | OptionsOpinionated, _: boolean): Promise<Nullable<StylelintOverrideConfig>>;
export declare function lumirelle(_?: OptionsConfig, ..._: Awaitable<StylelintConfig | StylelintOverrideConfig>[]): ConfigComposer;
export declare function ordered(_: boolean): Promise<Nullable<StylelintConfig>>;
export declare function resolvePackagePath(_: string): string;
export declare function resolvePackagePaths(_: string[]): string[];
export declare function scss(_: boolean, _: boolean | OptionsOpinionated): Promise<Nullable<StylelintOverrideConfig>>;
export declare function stylistic(_: boolean | StylisticConfig): Promise<Nullable<StylelintConfig>>;
export declare function tailwindcss(_: boolean): Promise<Nullable<StylelintConfig>>;
export declare function vue(_: boolean, _: boolean, _: boolean, _: boolean | OptionsOpinionated): Promise<Nullable<StylelintOverrideConfig>>;
// #endregion

// #region Variables
export declare const GLOB_EXCLUDE: string[];
// #endregion

// #region Default Export
declare function _default(_?: OptionsConfig, ..._: Awaitable<StylelintConfig | StylelintOverrideConfig>[]): ConfigComposer;
export default _default
// #endregion